GETGEMS_ADDRESS = "kQBZp2tZ9WUZQP8AgL2gUHkdJQe-8NyAcFksn3L7dcZxYJkN"  # noqa
TESTNET_GETGEMS_ADDRESS = "EQBYTuYbLf8INxFtD8tQeNk5ZLy-nAX9ahQbG_yl1qQ-GEMS"  # noqa

GETGEMS_FEE_ADDRESS = "kQD4FPq-PRDieyQKkizFTRtSDyucUIqrj0v_zXJmqaDp60an"  # noqa
TESTNET_GETGEMS_FEE_ADDRESS = "EQCjk1hh952vWaE9bRguFkAhDAL5jj3xj9p0uPWrFBq_GEMS"  # noqa

GETGEMS_DEPLOYER_ADDRESS = "EQAIFunALREOeQ99syMbO6sSzM_Fa1RsPD5TBoS0qVeKQ-AR"  # noqa
TESTNET_GETGEMS_DEPLOYER_ADDRESS = "kQDZwUjVjK__PvChXCvtCMshBT1hrPKMwzRhyTAtonUbL9i9"  # noqa
