DNS_NEXT_RESOLVER_CATEGORY = "dns_next_resolver"

DNS_WALLET_CATEGORY = "wallet"

DNS_SITE_CATEGORY = "site"

DNS_STORAGE_CATEGORY = "storage"

PREFIX_SITE_CATEGORY = 0xad01

PREFIX_WALLET_CATEGORY = 0x9fd3

PREFIX_STORAGE_CATEGORY = 0x7473

PREFIX_NEXT_RESOLVER_CATEGORY = 0xba93
