FACTORY_ADDRESS = "EQBfBWT7X2BHg9tXAxzhz2aKiNTU1tpt5NsiK0uSDW_YAJ67"  # noqa
TESTNET_FACTORY_ADDRESS = "kQDHcPxlCOSN_s-Vlw53bFpibNyKpZHV6xHhxGAAT_21nJre"  # noqa

NATIVE_VAULT_ADDRESS = "EQDa4VOnTYlLvDJ0gZjNYm5PXfSmmtL6Vs6A_CZEtXCNICq_"  # noqa
TESTNET_NATIVE_VAULT_ADDRESS = "kQDshQ2nyhezZleRdlZT12pvrj_cYp9XGmcRgYirA71DWlOb"  # noqa
